[tool.poetry]
name = "leomaine"
version = "0.1.0"
description = ""
authors = ["Shubham <shubhamprajapati8268@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
reflex = "^0.5.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
